apiVersion: v1
kind: Service
metadata:
  name: hello-aranya
  namespace: ayobami-app
  labels:
    app: hello-aranya
spec:
  selector:
    app: hello-aranya
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
