---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-cloud
  namespace: clusterdos-observability
type: Opaque
stringData:
  # see https://<instance-name>.grafana.net/a/grafana-collector-app/alloy?tab=installation
  # note: clustername is set by clusterdos.clustername
  prom-host: https://prometheus-prod-36-prod-us-west-0.grafana.net
  prom-username: "12345"
  loki-host: https://logs-prod-021.grafana.net
  loki-username: "67890"
  fleet-management-host: https://fleet-management-prod-014.grafana.net
  fleet-management-user: "112233"
  access-token: "changeme"
