---
apiVersion: v1
metadata:
  name: operator-oauth
  namespace: tailscale
kind: Secret
type: Opaque
stringData:
  # https://tailscale.com/kb/1236/kubernetes-operator#prerequisites
  # https://login.tailscale.com/admin/settings/oauth
  client_id: "CHANGEME"
  client_secret: "CHANGEME"
