[all:vars]
ansible_user=root
ansible_connection=ssh
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[kube_control_plane]
node1 ansible_host=134.199.193.57 ansible_port=22

[etcd]
node1 ansible_host=134.199.193.57 ansible_port=22

[kube_node]
node2 ansible_host=134.199.205.61 ansible_port=22
node3 ansible_host=134.199.198.44 ansible_port=22

[k8s_cluster:children]
kube_control_plane
kube_node
